##  Data Acquisiton, Cleaning, and Feature Engineering

## 1. Load Dataset

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv('H1.csv')
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NULL,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NULL,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [10]:
df.describe()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,Babies,IsRepeatedGuest,PreviousCancellations,PreviousBookingsNotCanceled,BookingChanges,DaysInWaitingList,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests
count,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.000000,40060.00000
mean,0.277634,92.675686,2016.121443,27.140864,15.821243,1.189815,3.128732,1.867149,0.128682,0.013904,0.044383,0.101722,0.146455,0.287968,0.527758,94.952930,0.138068,0.61977
std,0.447837,97.285315,0.722347,14.005441,8.883708,1.147812,2.461329,0.697285,0.445195,0.118998,0.205948,1.335115,1.001955,0.726548,7.428580,61.442418,0.351001,0.81393
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.00000
25%,0.000000,10.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.00000
50%,0.000000,57.000000,2016.000000,28.000000,16.000000,1.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,75.000000,0.000000,0.00000
75%,1.000000,155.000000,2017.000000,38.000000,24.000000,2.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,125.000000,0.000000,1.00000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,2.000000,1.000000,26.000000,30.000000,17.000000,185.000000,508.000000,8.000000,5.00000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40060 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   40060 non-null  int64
 1   LeadTime                     40060 non-null  int64
 2   ArrivalDateYear              40060 non-null  int64
 3   ArrivalDateMonth             40060 non-null  object
 4   ArrivalDateWeekNumber        40060 non-null  int64
 5   ArrivalDateDayOfMonth        40060 non-null  int64
 6   StaysInWeekendNights         40060 non-null  int64
 7   StaysInWeekNights            40060 non-null  int64
 8   Adults                       40060 non-null  int64
 9   Children                     40060 non-null  int64
 10  Babies                       40060 non-null  int64
 11  Meal                         40060 non-null  object
 12  Country                      39596 non-null  object
 13  MarketSegment                40060 non-null  object
 14  DistributionChannel          40060 non-null  object
 15  IsRepeatedGuest              40060 non-null  int64
 16  PreviousCancellations        40060 non-null  int64
 17  PreviousBookingsNotCanceled  40060 non-null  int64
 18  ReservedRoomType             40060 non-null  object
 19  AssignedRoomType             40060 non-null  object
 20  BookingChanges               40060 non-null  int64
 21  DepositType                  40060 non-null  object
 22  Agent                        40060 non-null  object
 23  Company                      40060 non-null  object
 24  DaysInWaitingList            40060 non-null  int64
 25  CustomerType                 40060 non-null  object
 26  ADR                          40060 non-null  float64
 27  RequiredCarParkingSpaces     40060 non-null  int64
 28  TotalOfSpecialRequests       40060 non-null  int64
 29  ReservationStatus            40060 non-null  object
 30  ReservationStatusDate        40060 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 9.5+ MB

## 2. Handle 'NULL' Text Values

In [12]:
# Strip spaces
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Replace NULL-like values
null_values = ['NULL', 'null', 'NaN', 'nan', 'None', '']
df = df.replace(null_values, np.nan)

df.isnull().sum()

IsCanceled                         0
LeadTime                           0
ArrivalDateYear                    0
ArrivalDateMonth                   0
ArrivalDateWeekNumber              0
ArrivalDateDayOfMonth              0
StaysInWeekendNights               0
StaysInWeekNights                  0
Adults                             0
Children                           0
Babies                             0
Meal                               0
Country                          464
MarketSegment                      0
DistributionChannel                0
IsRepeatedGuest                    0
PreviousCancellations              0
PreviousBookingsNotCanceled        0
ReservedRoomType                   0
AssignedRoomType                   0
BookingChanges                     0
DepositType                        0
Agent                           8209
Company                        36952
DaysInWaitingList                  0
CustomerType                       0
ADR                                0
RequiredCarParkingSpaces           0
TotalOfSpecialRequests             0
ReservationStatus                  0
ReservationStatusDate              0
dtype: int64

In [13]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40060 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   40060 non-null  int64
 1   LeadTime                     40060 non-null  int64
 2   ArrivalDateYear              40060 non-null  int64
 3   ArrivalDateMonth             40060 non-null  object
 4   ArrivalDateWeekNumber        40060 non-null  int64
 5   ArrivalDateDayOfMonth        40060 non-null  int64
 6   StaysInWeekendNights         40060 non-null  int64
 7   StaysInWeekNights            40060 non-null  int64
 8   Adults                       40060 non-null  int64
 9   Children                     40060 non-null  int64
 10  Babies                       40060 non-null  int64
 11  Meal                         40060 non-null  object
 12  Country                      39596 non-null  object
 13  MarketSegment                40060 non-null  object
 14  DistributionChannel          40060 non-null  object
 15  IsRepeatedGuest              40060 non-null  int64
 16  PreviousCancellations        40060 non-null  int64
 17  PreviousBookingsNotCanceled  40060 non-null  int64
 18  ReservedRoomType             40060 non-null  object
 19  AssignedRoomType             40060 non-null  object
 20  BookingChanges               40060 non-null  int64
 21  DepositType                  40060 non-null  object
 22  Agent                        31851 non-null  object
 23  Company                      3108 non-null   object
 24  DaysInWaitingList            40060 non-null  int64
 25  CustomerType                 40060 non-null  object
 26  ADR                          40060 non-null  float64
 27  RequiredCarParkingSpaces     40060 non-null  int64
 28  TotalOfSpecialRequests       40060 non-null  int64
 29  ReservationStatus            40060 non-null  object
 30  ReservationStatusDate        40060 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 9.5+ MB

## 3. Missing Value Treatment

In [8]:
# Numerical
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Categorical
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [15]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40060 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   40060 non-null  int64
 1   LeadTime                     40060 non-null  int64
 2   ArrivalDateYear              40060 non-null  int64
 3   ArrivalDateMonth             40060 non-null  object
 4   ArrivalDateWeekNumber        40060 non-null  int64
 5   ArrivalDateDayOfMonth        40060 non-null  int64
 6   StaysInWeekendNights         40060 non-null  int64
 7   StaysInWeekNights            40060 non-null  int64
 8   Adults                       40060 non-null  int64
 9   Children                     40060 non-null  int64
 10  Babies                       40060 non-null  int64
 11  Meal                         40060 non-null  object
 12  Country                      40060 non-null  object
 13  MarketSegment                40060 non-null  object
 14  DistributionChannel          40060 non-null  object
 15  IsRepeatedGuest              40060 non-null  int64
 16  PreviousCancellations        40060 non-null  int64
 17  PreviousBookingsNotCanceled  40060 non-null  int64
 18  ReservedRoomType             40060 non-null  object
 19  AssignedRoomType             40060 non-null  object
 20  BookingChanges               40060 non-null  int64
 21  DepositType                  40060 non-null  object
 22  Agent                        40060 non-null  object
 23  Company                      40060 non-null  object
 24  DaysInWaitingList            40060 non-null  int64
 25  CustomerType                 40060 non-null  object
 26  ADR                          40060 non-null  float64
 27  RequiredCarParkingSpaces     40060 non-null  int64
 28  TotalOfSpecialRequests       40060 non-null  int64
 29  ReservationStatus            40060 non-null  object
 30  ReservationStatusDate        40060 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 9.5+ MB

## 4. Remove Duplicates

In [16]:
df = df.drop_duplicates()

In [17]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   33968 non-null  int64
 1   LeadTime                     33968 non-null  int64
 2   ArrivalDateYear              33968 non-null  int64
 3   ArrivalDateMonth             33968 non-null  object
 4   ArrivalDateWeekNumber        33968 non-null  int64
 5   ArrivalDateDayOfMonth        33968 non-null  int64
 6   StaysInWeekendNights         33968 non-null  int64
 7   StaysInWeekNights            33968 non-null  int64
 8   Adults                       33968 non-null  int64
 9   Children                     33968 non-null  int64
 10  Babies                       33968 non-null  int64
 11  Meal                         33968 non-null  object
 12  Country                      33522 non-null  object
 13  MarketSegment                33968 non-null  object
 14  DistributionChannel          33968 non-null  object
 15  IsRepeatedGuest              33968 non-null  int64
 16  PreviousCancellations        33968 non-null  int64
 17  PreviousBookingsNotCanceled  33968 non-null  int64
 18  ReservedRoomType             33968 non-null  object
 19  AssignedRoomType             33968 non-null  object
 20  BookingChanges               33968 non-null  int64
 21  DepositType                  33968 non-null  object
 22  Agent                        27362 non-null  object
 23  Company                      2477 non-null   object
 24  DaysInWaitingList            33968 non-null  int64
 25  CustomerType                 33968 non-null  object
 26  ADR                          33968 non-null  float64
 27  RequiredCarParkingSpaces     33968 non-null  int64
 28  TotalOfSpecialRequests       33968 non-null  int64
 29  ReservationStatus            33968 non-null  object
 30  ReservationStatusDate        33968 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 8.3+ MB

## 5. Fix Data Types

In [19]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='ignore')

In [20]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## 6.Standardize Column Names

In [21]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [22]:
df.head()

,iscanceled,leadtime,arrivaldateyear,arrivaldatemonth,arrivaldateweeknumber,arrivaldatedayofmonth,staysinweekendnights,staysinweeknights,adults,children,...,deposittype,agent,company,daysinwaitinglist,customertype,adr,requiredcarparkingspaces,totalofspecialrequests,reservationstatus,reservationstatusdate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   iscanceled                   33968 non-null  int64
 1   leadtime                     33968 non-null  int64
 2   arrivaldateyear              33968 non-null  int64
 3   arrivaldatemonth             33968 non-null  object
 4   arrivaldateweeknumber        33968 non-null  int64
 5   arrivaldatedayofmonth        33968 non-null  int64
 6   staysinweekendnights         33968 non-null  int64
 7   staysinweeknights            33968 non-null  int64
 8   adults                       33968 non-null  int64
 9   children                     33968 non-null  int64
 10  babies                       33968 non-null  int64
 11  meal                         33968 non-null  object
 12  country                      33522 non-null  object
 13  marketsegment                33968 non-null  object
 14  distributionchannel          33968 non-null  object
 15  isrepeatedguest              33968 non-null  int64
 16  previouscancellations        33968 non-null  int64
 17  previousbookingsnotcanceled  33968 non-null  int64
 18  reservedroomtype             33968 non-null  object
 19  assignedroomtype             33968 non-null  object
 20  bookingchanges               33968 non-null  int64
 21  deposittype                  33968 non-null  object
 22  agent                        27362 non-null  float64
 23  company                      2477 non-null   float64
 24  daysinwaitinglist            33968 non-null  int64
 25  customertype                 33968 non-null  object
 26  adr                          33968 non-null  float64
 27  requiredcarparkingspaces     33968 non-null  int64
 28  totalofspecialrequests       33968 non-null  int64
 29  reservationstatus            33968 non-null  object
 30  reservationstatusdate        33968 non-null  object
dtypes: float64(3), int64(17), object(11)
memory usage: 8.3+ MB

In [24]:
df['reservationstatusdate'] = pd.to_datetime(
    df['reservationstatusdate'],
    format='%Y-%m-%d',   # enforce correct format
    errors='coerce'
)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   iscanceled                   33968 non-null  int64
 1   leadtime                     33968 non-null  int64
 2   arrivaldateyear              33968 non-null  int64
 3   arrivaldatemonth             33968 non-null  object
 4   arrivaldateweeknumber        33968 non-null  int64
 5   arrivaldatedayofmonth        33968 non-null  int64
 6   staysinweekendnights         33968 non-null  int64
 7   staysinweeknights            33968 non-null  int64
 8   adults                       33968 non-null  int64
 9   children                     33968 non-null  int64
 10  babies                       33968 non-null  int64
 11  meal                         33968 non-null  object
 12  country                      33522 non-null  object
 13  marketsegment                33968 non-null  object
 14  distributionchannel          33968 non-null  object
 15  isrepeatedguest              33968 non-null  int64
 16  previouscancellations        33968 non-null  int64
 17  previousbookingsnotcanceled  33968 non-null  int64
 18  reservedroomtype             33968 non-null  object
 19  assignedroomtype             33968 non-null  object
 20  bookingchanges               33968 non-null  int64
 21  deposittype                  33968 non-null  object
 22  agent                        27362 non-null  float64
 23  company                      2477 non-null   float64
 24  daysinwaitinglist            33968 non-null  int64
 25  customertype                 33968 non-null  object
 26  adr                          33968 non-null  float64
 27  requiredcarparkingspaces     33968 non-null  int64
 28  totalofspecialrequests       33968 non-null  int64
 29  reservationstatus            33968 non-null  object
 30  reservationstatusdate        33968 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(17), object(10)
memory usage: 8.3+ MB

In [26]:
df.head()

,iscanceled,leadtime,arrivaldateyear,arrivaldatemonth,arrivaldateweeknumber,arrivaldatedayofmonth,staysinweekendnights,staysinweeknights,adults,children,...,deposittype,agent,company,daysinwaitinglist,customertype,adr,requiredcarparkingspaces,totalofspecialrequests,reservationstatus,reservationstatusdate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## 6. Feature Engineering

In [27]:
df['totalstay'] = df['staysinweeknights'] + df['staysinweekendnights']

In [28]:
df['res_year'] = df['reservationstatusdate'].dt.year
df['res_month'] = df['reservationstatusdate'].dt.month
df['res_day'] = df['reservationstatusdate'].dt.day
df['res_weekday'] = df['reservationstatusdate'].dt.weekday

In [29]:
df['pricepernight'] = df['adr'] / (df['staysinweekendnights'] + 1)

In [30]:
df.head()

,iscanceled,leadtime,arrivaldateyear,arrivaldatemonth,arrivaldateweeknumber,arrivaldatedayofmonth,staysinweekendnights,staysinweeknights,adults,children,...,requiredcarparkingspaces,totalofspecialrequests,reservationstatus,reservationstatusdate,totalstay,res_year,res_month,res_day,res_weekday,pricepernight
0,0,342,2015,July,27,1,0,0,2,0,...,0,0,Check-Out,2015-07-01,0,2015,7,1,2,0.0
1,0,737,2015,July,27,1,0,0,2,0,...,0,0,Check-Out,2015-07-01,0,2015,7,1,2,0.0
2,0,7,2015,July,27,1,0,1,1,0,...,0,0,Check-Out,2015-07-02,1,2015,7,2,3,75.0
3,0,13,2015,July,27,1,0,1,1,0,...,0,0,Check-Out,2015-07-02,1,2015,7,2,3,75.0
4,0,14,2015,July,27,1,0,2,2,0,...,0,1,Check-Out,2015-07-03,2,2015,7,3,4,98.0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   iscanceled                   33968 non-null  int64
 1   leadtime                     33968 non-null  int64
 2   arrivaldateyear              33968 non-null  int64
 3   arrivaldatemonth             33968 non-null  object
 4   arrivaldateweeknumber        33968 non-null  int64
 5   arrivaldatedayofmonth        33968 non-null  int64
 6   staysinweekendnights         33968 non-null  int64
 7   staysinweeknights            33968 non-null  int64
 8   adults                       33968 non-null  int64
 9   children                     33968 non-null  int64
 10  babies                       33968 non-null  int64
 11  meal                         33968 non-null  object
 12  country                      33522 non-null  object
 13  marketsegment                33968 non-null  object
 14  distributionchannel          33968 non-null  object
 15  isrepeatedguest              33968 non-null  int64
 16  previouscancellations        33968 non-null  int64
 17  previousbookingsnotcanceled  33968 non-null  int64
 18  reservedroomtype             33968 non-null  object
 19  assignedroomtype             33968 non-null  object
 20  bookingchanges               33968 non-null  int64
 21  deposittype                  33968 non-null  object
 22  agent                        27362 non-null  float64
 23  company                      2477 non-null   float64
 24  daysinwaitinglist            33968 non-null  int64
 25  customertype                 33968 non-null  object
 26  adr                          33968 non-null  float64
 27  requiredcarparkingspaces     33968 non-null  int64
 28  totalofspecialrequests       33968 non-null  int64
 29  reservationstatus            33968 non-null  object
 30  reservationstatusdate        33968 non-null  datetime64[ns]
 31  totalstay                    33968 non-null  int64
 32  res_year                     33968 non-null  int32
 33  res_month                    33968 non-null  int32
 34  res_day                      33968 non-null  int32
 35  res_weekday                  33968 non-null  int32
 36  pricepernight                33968 non-null  float64
dtypes: datetime64[ns](1), float64(4), int32(4), int64(18), object(10)
memory usage: 9.3+ MB

## 8. Outlier Removal (IQR Method)

In [47]:
# Remove negative ADR (invalid)
df_cleanednegative = df[df['adr'] >= 0]

In [48]:
df_cleanednegative.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33967 entries, 0 to 40059
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   iscanceled                   33967 non-null  int64
 1   leadtime                     33967 non-null  int64
 2   arrivaldateyear              33967 non-null  int64
 3   arrivaldatemonth             33967 non-null  object
 4   arrivaldateweeknumber        33967 non-null  int64
 5   arrivaldatedayofmonth        33967 non-null  int64
 6   staysinweekendnights         33967 non-null  int64
 7   staysinweeknights            33967 non-null  int64
 8   adults                       33967 non-null  int64
 9   children                     33967 non-null  int64
 10  babies                       33967 non-null  int64
 11  meal                         33967 non-null  object
 12  country                      33521 non-null  object
 13  marketsegment                33967 non-null  object
 14  distributionchannel          33967 non-null  object
 15  isrepeatedguest              33967 non-null  int64
 16  previouscancellations        33967 non-null  int64
 17  previousbookingsnotcanceled  33967 non-null  int64
 18  reservedroomtype             33967 non-null  object
 19  assignedroomtype             33967 non-null  object
 20  bookingchanges               33967 non-null  int64
 21  deposittype                  33967 non-null  object
 22  agent                        27361 non-null  float64
 23  company                      2477 non-null   float64
 24  daysinwaitinglist            33967 non-null  int64
 25  customertype                 33967 non-null  object
 26  adr                          33967 non-null  float64
 27  requiredcarparkingspaces     33967 non-null  int64
 28  totalofspecialrequests       33967 non-null  int64
 29  reservationstatus            33967 non-null  object
 30  reservationstatusdate        33967 non-null  datetime64[ns]
 31  totalstay                    33967 non-null  int64
 32  res_year                     33967 non-null  int32
 33  res_month                    33967 non-null  int32
 34  res_day                      33967 non-null  int32
 35  res_weekday                  33967 non-null  int32
 36  pricepernight                33967 non-null  float64
dtypes: datetime64[ns](1), float64(4), int32(4), int64(18), object(10)
memory usage: 9.3+ MB

In [49]:
df_cleanednegative['adr'].max()

508.0

In [50]:
Q1 = df_cleanednegative['adr'].quantile(0.25)
Q3 = df_cleanednegative['adr'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower:", lower, "Upper:", upper)

Lower: -72.5 Upper: 257.9

In [51]:
upper = df_cleanednegative['adr'].quantile(0.99)
lower = df_cleanednegative['adr'].quantile(0.01)

df_cleanednegative['adr'] = df_cleanednegative['adr'].clip(lower, upper)

C:\Users\USER\AppData\Local\Temp\ipykernel_6296\699357045.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleanednegative['adr'] = df_cleanednegative['adr'].clip(lower, upper)

C:\Users\USER\AppData\Local\Temp\ipykernel_6296\2783347060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleanednegative['adr'] = df_cleanednegative['adr'].clip(lower, upper)